import { env } from "./env.js";

export const envKeys = {
  PORT: +(env.PORT ?? 8000),
  JWT_SECRET: env.JWT_SECRET,
  MONGO_URL: env.MONGO_URL,
  CLIENT_URL: env.CLIENT_URL,
  NODE_ENV: env.NODE_ENV,
  OPTION: env.OPTION,
  PINECONE_API_KEY: env.PINECONE_API_KEY,
  PINECONE_INDEX_NAME: env.PINECONE_INDEX_NAME,
  HUGGINGFACE_API_KEY: env.HUGGINGFACE_API_KEY,
};
